### ISSUE TITLE
Can't compare size when searching

### ISSUE THREAD

**Issue by mxd008** [5elenay/datagoose#1]
Good performance but Can't compare size when searching

**Comment by 5elenay** [comment]
Can you explain what do you mean with "Can't compare size when searching"? if you are trying to say query search like `"age" > 10`, Yes. datagoose currently don't support this usage. But that doesn't mean you can't compare values while search. You can make this manually while datagoose don't have this feature. I added this issue to my todo list, and i will add this feature in next update.
